---
title: The Ivy Project
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  visuals:
    title: Visuals
    output: true
    permalink: "/visuals/:title/"
  work:
    title: Work
    output: true
    permalink: "/work/:title/"
email: montier.kess@gmail.com
description: 'Portfolio brand for Montier Kess (@waterme.ivy)

'
baseurl: ''
url: ''
markdown: kramdown
theme: minima
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
