# Site settings
title: The Ivy Project
email: montier.kess@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Portfolio brand for Montier Kess (@waterme.ivy)
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

collections:
  work:
    output: true
    permalink: /work/:title/

  visuals:
    output: true
    permalink: /visuals/:title/